<?php
unset($_SESSION['legajo']);
unset($_SESSION['carrera']);
unset($_SESSION['dni_profesor']);
unset($_SESSION['nombre_empresa']);
unset($_SESSION['direccion_empresa']);
unset($_SESSION['telefono_empresa']);
unset($_SESSION['modalidad_trabajo']);
unset($_SESSION['nombre_jefe']);
unset($_SESSION['apellido_jefe']);
unset($_SESSION['email_jefe']);
